name: Windows
# Complete packaging in the future

on:
  push:
    branches:
      - feat/package
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        qt_ver: [6.6.3]
        qt_arch: [win64_msvc2019_64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup Rust toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Cache corrosion
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/build/_deps
          ${{ github.workspace }}/build/*/cargo/build
          !${{ github.workspace }}/build/*/cargo/build/**/incremental
          ${{ github.workspace }}/build/corrosion/**/target
          !${{ github.workspace }}/build/corrosion/**/target/**/incremental
        key: corrosion-${{ runner.os }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_ver }}
        cache: true
        arch: ${{ matrix.qt_arch }}

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgConfigurationJsonGlob: 'vcpkg-configuration.json'
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Build with CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'msvc-x64'

    - name: Package with Inno-Setup
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: ./action-cli/InstallerScript.iss
        options: /O+
